linux: Enable EFI booting for GRUB 2.04
GRUB 2.04 on ARM requires an EFI Boot Stub, which allows EFI firmware to
load the kernel as an EFI executable.

Fixes GRUB error:

    error: plain image kernel not supported - rebuild with
    CONFIG_(U)EFI_STUB enabled.

Message after enabling CONFIG_EFI_STUB:

    EFI stub: Booting Linux Kernel...
    EFI stub: Using DTB from configuration table
    EFI stub: Exiting boot services and installing virtual address map...